# Generated by Django 5.0.1 on 2024-01-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('population', models.IntegerField()),
                ('is_capital', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('population', models.IntegerField()),
                ('government', models.CharField(blank=True, choices=[('democracy', 'Democracy'), ('republic', 'Republic'), ('monarchy', 'Monarchy'), ('communism', 'Communism'), ('dictatorship', 'Dictatorship')], default='democracy', max_length=100, null=True)),
                ('capital', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='world_app.city')),
                ('cities', models.ManyToManyField(blank=True, related_name='countries', to='world_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('population', models.IntegerField()),
                ('countries', models.ManyToManyField(related_name='continents', to='world_app.country')),
            ],
        ),
    ]
